"""Typed access to the canonical design token source (static/design-tokens.json).

The JSON file is the only hand-maintained palette. Every consumer (Python,
Tailwind, CSS) reads from it; this module validates it at import and exposes
typed helpers for dotted paths (e.g. color("burgundy.400"),
palette("chart.exercise")). It never writes at runtime.
"""

import json
import re
from functools import lru_cache
from pathlib import Path

_TOKEN_FILE = Path(__file__).resolve().parents[1] / "static" / "design-tokens.json"

_REQUIRED_SECTIONS = {"surfaces", "burgundy", "focus", "semantics", "chart"}
_REQUIRED_SURFACES = {"matte", "neutral"}
_BURGUNDY_SCALE = {"50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"}
_HEX_RE = re.compile(r"^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$")
_RGBA_RE = re.compile(r"^rgba?\([^)]*\)$")


class TokenError(KeyError):
    """Raised when a token path does not exist in the canonical JSON."""


def _validate(tokens: dict) -> None:
    missing = _REQUIRED_SECTIONS - set(tokens)
    if missing:
        raise TokenError(f"design-tokens.json missing sections: {sorted(missing)}")
    if not _REQUIRED_SURFACES <= set(tokens["surfaces"]):
        raise TokenError("design-tokens.json missing matte/neutral surfaces")
    if not _BURGUNDY_SCALE <= set(tokens["burgundy"]):
        raise TokenError("design-tokens.json burgundy scale is incomplete")
    if (
        not isinstance(tokens["chart"].get("exercise"), list)
        or len(tokens["chart"]["exercise"]) < 5
    ):
        raise TokenError("design-tokens.json chart.exercise must be a palette of 5+ colors")
    for path, value in _walk(tokens):
        if not isinstance(value, str) or path.startswith(("schema_version", "glow.")):
            continue
        if not (_HEX_RE.match(value) or _RGBA_RE.match(value)):
            raise TokenError(f"design-tokens.json {path}: not a color: {value!r}")


def _walk(obj: dict, prefix: str = ""):
    for key, value in obj.items():
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            yield from _walk(value, path)
        elif isinstance(value, list):
            for i, item in enumerate(value):
                yield f"{path}.{i}", item
        else:
            yield path, value


@lru_cache(maxsize=1)
def read_tokens() -> dict:
    """Parsed and validated canonical tokens (cached for the process)."""
    tokens = json.loads(_TOKEN_FILE.read_text(encoding="utf-8"))
    _validate(tokens)
    return tokens


def _lookup(path: str):
    current = read_tokens()
    for part in path.split("."):
        try:
            current = current[part]
        except (KeyError, TypeError):
            raise TokenError(f"unknown design token: {path!r}") from None
    return current


def color(path: str) -> str:
    """Single color value at a dotted path (e.g. "burgundy.400", "chart.axes")."""
    value = _lookup(path)
    if not isinstance(value, str):
        raise TokenError(f"design token {path!r} is not a color")
    return value


def palette(path: str) -> list[str]:
    """Color list at a dotted path (e.g. "chart.exercise")."""
    value = _lookup(path)
    if not isinstance(value, list) or not all(isinstance(v, str) for v in value):
        raise TokenError(f"design token {path!r} is not a palette")
    return list(value)


def render_css(tokens: dict) -> str:
    """Deterministic CSS custom properties from the canonical JSON.

    Each dotted token becomes --t-<path> (palette entries get a -<index>
    suffix). Deterministic: insertion order of the JSON + sorted traversal.
    """
    lines = [
        "/* tokens.css — GENERATED by scripts/build_design_tokens.py. Do not edit. */",
        "/* Canonical source: static/design-tokens.json. */",
        ":root {",
    ]
    for path, value in _walk(tokens):
        if path == "schema_version":
            continue
        var = "--t-" + path.replace(".", "-").replace("/", "-")
        lines.append(f"  {var}: {value};")
    lines.append("}")
    return "\n".join(lines) + "\n"
